### ISSUE TITLE
Cannot build using aapt

### ISSUE THREAD

**Issue by zwpwjwtz** [jgerace/SMSBackup#1]
I tried to build this project using Android SDK 24.4, but then encountered following problem:
```
$ aapt package -f -m -J build -I /media/user/Programme/android-sdk-linux/platforms/android-19/android.jar -M AndroidManifest.xml 
AndroidManifest.xml:15: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/ic_launcher').

AndroidManifest.xml:15: error: Error: No resource found that matches the given name (at 'label' with value '@string/app_name').

AndroidManifest.xml:15: error: Error: No resource found that matches the given name (at 'theme' with value '@style/AppTheme').

AndroidManifest.xml:20: error: Error: No resource found that matches the given name (at 'label' with value '@string/app_name').
```
It seems that "appcompat" is not included explicitly. Could you tell me how to specify the path of missing library, or how to fix this dependency problem? I'm new to Android & Java.

**Comment by jgerace** [comment]
Correct. I didn't include that stuff purposefully and I probably shouldn't have included many of the other project files in this repo. To be honest, this is the first and only Android app I've written, so my advice may not be very helpful. You might want to try creating a new project and copying the permissions from the AndroidManifest.xml file into the one the SDK creates for you or add them via the interface in the IDE. Then copy the .java files from the repo's src directory into the corresponding src directory in your project.

**Comment by zwpwjwtz** [comment]
So this means it's not easy to fix dependencies using command line?

**Comment by jgpeloton** [comment]
Unfortunately, I wouldn't know.

**Comment by jgerace** [comment]
Unfortunately, I wouldn't know.
